<-DefaultButton>:
    background_normal: 'resources/default_button_normal.png'
    background_down: 'resources/default_button_down.png'
    state_image: self.background_normal if self.state == 'normal' else self.background_down

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            size: self.size
            pos: self.pos
            source: self.state_image

    size_hint: None, None
    size: '20dp', '20dp'
