#:include game/gui/minesweeper/desktop/field_config/field_config.kv
#:include game/gui/minesweeper/desktop/game_achievements/game_achievements.kv
#:include game/gui/minesweeper/desktop/statistics/statistics.kv
#:include game/gui/minesweeper/desktop/achievements/achievements.kv
#:include game/gui/minesweeper/desktop/authentication/authentication.kv

#:include game/gui/minesweeper/desktop/game_field/game_field.kv
#:include game/gui/minesweeper/desktop/root_window/root_window.kv
